### ISSUE TITLE
Audio Capture

### ISSUE THREAD

**Issue by PaitoAnderson** [manishganvir/iOS-h264Hw-Toolbox#2]
It would be nice if this example also captured and encoded audio.

**Comment by manishganvir** [comment]
If the purpose is to create a container like mp4 then AVCapture APIs and AVAssetWriter would do that. 

Steps:

1) AVCapture for audio
2) AVCapture for video
3) AVAssetWriter with audio and video inputs
4) Providing audio/video data to the inputs

From my understanding, iOS does not provide hardware accelerated APIs to get encoded audio in the application. However it allows us to write the same to a file. We can use software APIs however for the encoding.

My idea for this application is to have a sample which can be used in streaming applications. So I will add a <b>sample for audio which will allow us to capture raw PCM, encode it to opus</b>. Let me find some time for the same.
