### ISSUE TITLE
Adjust bitrate?

### ISSUE THREAD

**Issue by trentbrooks** [manishganvir/iOS-h264Hw-Toolbox#3]
Hey @manishganvir,

Thanks for the great VideoToolbox example - this is the clearest/easiest to understand example I've found. Just wondering how to adjust the bitrate - the exported video is extremely low quality? Setting the kVTCompressionPropertyKey_AverageBitRate doesn't seem to make a difference, no matter what value I use - http://stackoverflow.com/questions/31458150/how-to-set-bitrate-for-vtcompressionsession

Also, you mentioned in another issue you are testing this with a streaming application - just wondering how you are using the encoded data to send over network? eg. udp, rtsp, any external libraries?

Thanks,
Trent

**Comment by manishganvir** [comment]
I am using this example for webrtc based streaming using SRTP/DTLS. 

For getting better quality, you can change the resolution to higher value such as 1920x1080 or 720p. This can be done by starting the camera in this resolution and initializing the encoder with the same.

You can get the better encoded bit rate by tweaking the encoder options such as 

```
// VTSessionSetProperty(EncodingSession, kVTCompressionPropertyKey_RealTime, kCFBooleanTrue);
    VTSessionSetProperty(EncodingSession, kVTCompressionPropertyKey_AllowFrameReordering, kCFBooleanFalse);
    VTSessionSetProperty(EncodingSession, kVTCompressionPropertyKey_MaxKeyFrameInterval, (__bridge CFNumberRef)@(240));
    VTSessionSetProperty(EncodingSession, kVTCompressionPropertyKey_AverageBitRate, (__bridge CFNumberRef)@(5000*1024));
```
